## How-to-count-distance-to-the-previous-zero
For each value, count the difference of the distance from the previous zero (or the start of the Series, whichever is closer) and if there are no previous zeros,print the position

Consider a DataFrame df where there is an integer column {'X':[7, 2, 0, 3, 4, 2, 5, 0, 3, 4]}

The values should therefore be [1, 2, 0, 1, 2, 3, 4, 0, 1, 2]. Make this a new column 'Y'.import pandas as pd

df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame({'X':[7,2,0,3,4,2,5,0,3,4]})
#calulate the indexes of zero
zeroIndex = np.r_[-1, (df['X'] == 0).nonzero()[0]] 
print(zeroIndex)
idx = np.arange(len(df))
print(idx)
df['Y'] = idx - zeroIndex[np.searchsorted(zeroIndex - 1, idx) - 1]

[-1  2  7]
[0 1 2 3 4 5 6 7 8 9]


In [4]:
df

X  Y
0  7  1
1  2  2
2  0  0
3  3  1
4  4  2
5  2  3
6  5  4
7  0  0
8  3  1
9  4  2

In [5]:
df['Y']

0    1
1    2
2    0
3    1
4    2
5    3
6    4
7    0
8    1
9    2
Name: Y, dtype: int64

In [6]:
np.array(df['Y'])

array([1, 2, 0, 1, 2, 3, 4, 0, 1, 2], dtype=int64)

## 2) Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of random numbers.

In [7]:
dt = pd.date_range(start='2015-01-01', end='2015-12-31', freq='B') 
s = pd.Series(np.random.rand(len(dt)), index=dt)
s

2015-01-01    0.104841
2015-01-02    0.033431
2015-01-05    0.412064
2015-01-06    0.640670
2015-01-07    0.291326
2015-01-08    0.817841
2015-01-09    0.129695
2015-01-12    0.680156
2015-01-13    0.905405
2015-01-14    0.005112
2015-01-15    0.663480
2015-01-16    0.772494
2015-01-19    0.943609
2015-01-20    0.227627
2015-01-21    0.428026
2015-01-22    0.345281
2015-01-23    0.516040
2015-01-26    0.247265
2015-01-27    0.974143
2015-01-28    0.010525
2015-01-29    0.825233
2015-01-30    0.397571
2015-02-02    0.720022
2015-02-03    0.689555
2015-02-04    0.012669
2015-02-05    0.822471
2015-02-06    0.061251
2015-02-09    0.550108
2015-02-10    0.840918
2015-02-11    0.105295
                ...   
2015-11-20    0.793780
2015-11-23    0.765042
2015-11-24    0.008326
2015-11-25    0.532410
2015-11-26    0.082778
2015-11-27    0.006496
2015-11-30    0.659459
2015-12-01    0.605215
2015-12-02    0.259125
2015-12-03    0.535001
2015-12-04    0.426239
2015-12-07    0.153649
2015-12-08 

## 3) Find the sum of the values in s for every Wednesday

In [8]:
s[dt.weekday == 2].sum() 

24.393885754979536

## 4) Average For each calendar month

In [9]:
s.resample('M', how='mean')

F:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: how in .resample() is deprecated
the new syntax is .resample(...).mean()
  """Entry point for launching an IPython kernel.


2015-01-31    0.471447
2015-02-28    0.539922
2015-03-31    0.498839
2015-04-30    0.498562
2015-05-31    0.456015
2015-06-30    0.485706
2015-07-31    0.544358
2015-08-31    0.607374
2015-09-30    0.439422
2015-10-31    0.506907
2015-11-30    0.512331
2015-12-31    0.524530
Freq: M, dtype: float64

In [10]:
s.resample('M').mean()

2015-01-31    0.471447
2015-02-28    0.539922
2015-03-31    0.498839
2015-04-30    0.498562
2015-05-31    0.456015
2015-06-30    0.485706
2015-07-31    0.544358
2015-08-31    0.607374
2015-09-30    0.439422
2015-10-31    0.506907
2015-11-30    0.512331
2015-12-31    0.524530
Freq: M, dtype: float64

## 5) For each group of four consecutive calendar months in s, find the date on which the highest value occurred.

In [11]:
s.groupby(pd.TimeGrouper('4M')).idxmax()

F:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: pd.TimeGrouper is deprecated and will be removed; Please use pd.Grouper(freq=...)
  """Entry point for launching an IPython kernel.


2015-01-31   2015-01-27
2015-05-31   2015-02-17
2015-09-30   2015-07-24
2016-01-31   2015-10-28
dtype: datetime64[ns]

In [12]:
s.groupby(pd.Grouper(freq='4M')).idxmax()

2015-01-31   2015-01-27
2015-05-31   2015-02-17
2015-09-30   2015-07-24
2016-01-31   2015-10-28
dtype: datetime64[ns]